[phases.setup]
nixPkgs = ['python311', 'poetry', 'ffmpeg']

[phases.install]
cmds = [
  'poetry install --without dev'
]

[start]
cmd = 'export PYTHONPATH=/app/src:$PYTHONPATH && poetry run uvicorn expenses_bot.backend_:app --host 0.0.0.0 --port $PORT'
